name: Flush to Amazon ECS

on:
  workflow_dispatch:
env:
  CLOUDFRONT_DISTRIBUTION_ID: E19AK26SFJYOK4
  
jobs:
  build-info:
    name: Flush
    runs-on: ubuntu-latest
    steps:
    
      - name: Development Branch Detected
        if: ${{ needs.build-info.outputs.branch != 'master'}}
        run: |
            echo "CLOUDFRONT_DISTRIBUTION_ID=E28UBPK9Z0N99E" >> $GITHUB_ENV
            
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Invalidate Cloudfront CDN
        run: aws cloudfront create-invalidation --distribution-id=${{ env.CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*'

        
