name: Event Loggger
on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  log-github-event-goodies:
    name: "LOG Everything on GitHub Event"
    runs-on: ubuntu-latest
    steps:
      - name: Logging
        run: |
          echo github.event.head_commit.message

