name: demo

on:
  pull_request:
    branches:
      - develop
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  job1:
    env:
      commitmsg: ${{ github.event.head_commit.message }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: get commit message
        run: |
            echo Commit MSG = ${{ env.commitmsg }}
