name: demo

on:
  pull_request:
    branches:
      - develop
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  job1:
    env:
      commitmsg: ${{ github.event.head_commit.message }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: get commit message
        run: |
            echo Commit MSG = ${{ env.commitmsg }}

      - name: Check Fixes
        if: ${{ success() || failure() }}
        uses: tim-actions/commit-message-checker-with-regex@v0.3.1
        with:
          commits: ${{ steps.get-pr-commits.outputs.commits }}
          pattern: '\s*Fixes\s*:?\s*(#\d+|github\.com\/kata-containers\/[a-z-.]*#\d+)'
          error: 'No "Fixes" found'
          one_pass_all_pass: 'true'

      - name: Check subsystem
        if: ${{ success() || failure() }}
        uses: tim-actions/commit-message-checker-with-regex@v0.3.1
        with:
          commits: ${{ steps.get-pr-commits.outputs.commits }}
          pattern: '^[\h]*([^:\h\n]+)[\h]*:'
          error: 'Failed to find subsystem in subject'
