name: Event Loggger

on:
  pull_request:
    branches:
      - develop
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{github.event.after}}
      - name: Get Commit Message
        run: |
         echo: ${{ github.event.head_commit.message }}
