name: Build Main

on:
  push:
    branches:
      - develop
    tags:
      - 'v*'
  workflow_dispatch:

env:
  owner: ObsidianLabs
  own_components: eth-components
  share_components: electron-components
  project_build: eth
  project_project: eth
  project_name: Black IDE
  project_build_script: yarn && REACT_APP_ENV=development yarn dist
  enable_auth: false
  premium_editor: ../premium-editor
  GH_TOKEN: ${{ secrets.obsidians_token }}
  PR_NUMBER: ${{ github.event.number }}
